// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module '@useautumn/sdk' {
  // Features
  export const meeting_credits_v2: Feature;
  export const to_dos: Feature;

  // Plans
  export const pro: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
