// Auto-generated method signatures with JSDoc
// This file is generated by typegen pipeline from @useautumn/sdk
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To update documentation:
// 1. Edit JSDoc in backend server's shared/api directory
// 2. Regenerate OpenAPI spec and SDK
// 3. Run: pnpm run gen:autumn-js

import type { Autumn } from "@useautumn/sdk";
import type {
  AttachParams,
  CancelParams,
  CheckParams,
} from "@/clientTypes";

/**
 * Methods available in useEntity hook for entity-scoped subscription operations
 */
export interface UseEntityMethods {
  /**
   * Enables a product for a customer and processes payment if their payment method is already on file.
   * Use this when the customer already has a payment method saved.
   * For new customers without payment info, use `checkout` instead.
   *
   *
   * @example
   * ```typescript // Attach a product to a customer const response = await client.attach({ customer_id: "cus_123", product_id: "pro_plan", }); ```
   *
   * @see
   * {@link https://docs.useautumn.com/api-reference/core/attach Product Attachments}
   *
   * @example
   * ```ts const response = await client.attach({ customer_id: 'cus_123', product_id: 'pro_plan', }); ```
   */
  attach: (params: AttachParams) => Promise<Autumn.AttachResponse>;

  /**
   * Cancel a customer's subscription to a product.
   * Use this when a customer wants to stop their subscription.
   * Supports immediate or end-of-period cancellation.
   *
   * @param params.product_id - The ID of the product to cancel
   * @param params.entity_id - The ID of the entity (optional)
   * @param params.cancel_immediately - Whether to cancel the product immediately or at period end
   * @param params.prorate - Whether to prorate the cancellation (defaults to true if not specified)
   *
   * @example
   * ```typescript // Cancel a subscription const response = await client.cancel({ customer_id: "cus_123", product_id: "pro_plan", }); ```
   *
   * @see
   * {@link https://docs.useautumn.com/api-reference/core/cancel Cancel Subscriptions}
   *
   * @example
   * ```ts const response = await client.cancel({ customer_id: 'cus_123', product_id: 'pro_plan', }); ```
   */
  cancel: (params: CancelParams) => Promise<Autumn.CancelResponse>;

  /**
   * Creates a checkout session for a customer to purchase a product with payment collection.
   * Use this for new customers or when payment info is needed.
   * For customers with existing payment methods, use `attach` instead.
   *
   *
   * @example
   * ```typescript // Create a checkout session const response = await client.checkout({ customer_id: "cus_123", product_id: "pro_plan", }); ```
   *
   * @see
   * {@link https://docs.useautumn.com/api-reference/core/checkout Checkout Sessions}
   *
   * @example
   * ```ts const response = await client.check({ customer_id: 'customer_id', feature_id: 'feature_id', }); ```
   */
  check: (params: CheckParams) => Autumn.CheckResponse;
}
