// Auto-generated method signatures with JSDoc
// This file is generated by typegen pipeline from ts-sdk/src/client.ts
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To update documentation:
// 1. Edit JSDoc in backend server's shared/api directory
// 2. Regenerate OpenAPI spec and SDK
// 3. Run: pnpm run gen:autumn-js

import type { Autumn } from "@sdk";
import type {
  AttachParams,
  CancelParams,
  CheckParams,
} from "@/clientTypes";

/**
 * Methods available in useEntity hook for entity-scoped subscription operations
 */
export interface UseEntityMethods {
  /**
   * Enables a product for a customer and processes payment if their payment method is already on file.
   * Use this when the customer already has a payment method saved.
   * For new customers without payment info, use `checkout` instead.
   *
   * @param params.product_id - Product ID, set when creating the product in the Autumn dashboard
   * @param params.entity_id - If attaching a product to an entity, can be used to auto create the entity
   * @param params.customer_data - If auto creating a customer, the properties from this field will be used.
   * @param params.entity_data - If attaching a product to an entity and auto creating the entity, the properties from this field will be used. feature_id is required.
   * @param params.product_ids - Can be used to attach multiple products to the customer at once. For example, attaching a main product and an add-on.
   * @param params.options - Pass in quantities for prepaid features
   * @param params.free_trial - If the product has a free trial, this field can be used to disable it when attaching (by passing in false)
   * @param params.success_url - URL to redirect to after the purchase is successful
   * @param params.force_checkout - Always return a Stripe Checkout URL, even if the customer's card is already on file
   * @param params.checkout_session_params - Additional parameters to pass onto Stripe when creating the checkout session
   * @param params.reward - An Autumn promo_code or reward_id to apply at checkout
   *
   * @example
   * ```typescript // Attach a product to a customer const response = await client.attach({ customer_id: "cus_123", product_id: "pro_plan", }); ```
   *
   * @see
   * {@link https://docs.useautumn.com/api-reference/core/attach Product Attachments}
   *
   * @example
   * ```ts const response = await client.attach({ customer_id: 'cus_123', product_id: 'pro_plan', }); ```
   */
  attach: (params: AttachParams) => Promise<Autumn.AttachResponse>;

  /**
   * Cancel a customer's subscription to a product.
   * Use this when a customer wants to stop their subscription.
   * Supports immediate or end-of-period cancellation.
   *
   * @param params.product_id - The ID of the product to cancel
   * @param params.entity_id - The ID of the entity (optional)
   * @param params.cancel_immediately - Whether to cancel the product immediately or at period end
   * @param params.prorate - Whether to prorate the cancellation (defaults to true if not specified)
   *
   * @example
   * ```typescript // Cancel a subscription const response = await client.cancel({ customer_id: "cus_123", product_id: "pro_plan", }); ```
   *
   * @see
   * {@link https://docs.useautumn.com/api-reference/core/cancel Cancel Subscriptions}
   *
   * @example
   * ```ts const response = await client.cancel({ customer_id: 'cus_123', product_id: 'pro_plan', }); ```
   */
  cancel: (params: CancelParams) => Promise<Autumn.CancelResponse>;

  /**
   * Creates a checkout session for a customer to purchase a product with payment collection.
   * Use this for new customers or when payment info is needed.
   * For customers with existing payment methods, use `attach` instead.
   *
   * @param params.product_id - Product ID, set when creating the product in the Autumn dashboard
   * @param params.entity_id - If attaching a product to an entity, can be used to auto create the entity
   * @param params.customer_data - If auto creating a customer, the properties from this field will be used.
   * @param params.entity_data - If attaching a product to an entity and auto creating the entity, the properties from this field will be used. feature_id is required.
   * @param params.product_ids - Can be used to attach multiple products to the customer at once. For example, attaching a main product and an add-on.
   * @param params.options - Pass in quantities for prepaid features
   * @param params.free_trial - If the product has a free trial, this field can be used to disable it when attaching (by passing in false)
   * @param params.success_url - URL to redirect to after the purchase is successful
   * @param params.force_checkout - Always return a Stripe Checkout URL, even if the customer's card is already on file
   * @param params.checkout_session_params - Additional parameters to pass onto Stripe when creating the checkout session
   * @param params.reward - An Autumn promo_code or reward_id to apply at checkout
   *
   * @example
   * ```typescript // Create a checkout session const response = await client.checkout({ customer_id: "cus_123", product_id: "pro_plan", }); ```
   *
   * @see
   * {@link https://docs.useautumn.com/api-reference/core/checkout Checkout Sessions}
   *
   * @example
   * ```ts const response = await client.check({ customer_id: 'customer_id', }); ```
   */
  check: (params: CheckParams) => Autumn.CheckResponse;
}
