packages:
  - package
  - frameworks/*
  - nextjs
  - compose
  - cli
  - atmn
  - ui
  - test-worker
  - next15
  - next-bug
  - vite-spa
  - convex

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - msw
  - unrs-resolver

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
