import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import prettier from "prettier";
import type { Feature, Plan } from "../../../source/compose/models/index.js";
import { featureIdToVarName, planIdToVarName } from "../../lib/transforms/index.js";

/**
 * Generate SDK types file (@useautumn-sdk.d.ts)
 */
export async function generateSdkTypes(options: {
	features: Feature[];
	plans: Plan[];
	outputDir: string;
}): Promise<string> {
	const { features, plans, outputDir } = options;
	const outputPath = resolve(outputDir, "@useautumn-sdk.d.ts");

	// Generate type definitions
	const sections: string[] = [];

	// Header
	sections.push(`// AUTO-GENERATED by atmn pull`);
	sections.push(`// DO NOT EDIT MANUALLY`);
	sections.push(``);
	sections.push(`declare module '@useautumn/sdk' {`);
	sections.push(``);

	// Feature types
	if (features.length > 0) {
		sections.push(`  // Features`);
		for (const feature of features) {
			const varName = featureIdToVarName(feature.id);
			sections.push(`  export const ${varName}: Feature;`);
		}
		sections.push(``);
	}

	// Plan types
	if (plans.length > 0) {
		sections.push(`  // Plans`);
		for (const plan of plans) {
			const varName = planIdToVarName(plan.id);
			sections.push(`  export const ${varName}: Plan;`);
		}
		sections.push(``);
	}

	// Base types (reference autumn.config.ts)
	sections.push(`  // Base types`);
	sections.push(`  export type Feature = import('./autumn.config').Feature;`);
	sections.push(`  export type Plan = import('./autumn.config').Plan;`);
	sections.push(`}`);

	const code = sections.join("\n");

	// Format with prettier
	let formattedCode: string;
	try {
		formattedCode = await prettier.format(code, {
			parser: "typescript",
			useTabs: false,
			singleQuote: true,
		});
	} catch (error) {
		console.warn("Failed to format SDK types file:", error);
		formattedCode = code;
	}

	// Write file
	writeFileSync(outputPath, formattedCode, "utf-8");

	return outputPath;
}
