import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// layout.tsx

import { AutumnProvider } from "autumn-js/react";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full w-full min-w-screen">
			<body className="h-full m-0 p-0 w-full min-w-screen">
				<AutumnProvider>{children}</AutumnProvider>
			</body>
		</html>
	);
}
