import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// layout.tsx

import { AutumnProvider } from "autumn-js/react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full min-w-screen">
              <body className="h-full m-0 p-0 w-full min-w-screen">
        <AutumnProvider betterAuthUrl="http://localhost:3001">
          {children}
        </AutumnProvider>
      </body>
    </html>
  );
}
