// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module '@useautumn/sdk' {
  // Features
  export const chat_messages: Feature;
  export const editors: Feature;
  export const pages: Feature;
  export const domains: Feature;

  // Plans
  export const free: Plan;
  export const domains: Plan;
  export const startup: Plan;
  export const growth: Plan;
  export const ultra: Plan;
  export const volume_based_product: Plan;

  // Base types
  export type Feature = import('./autumn.config').Feature;
  export type Plan = import('./autumn.config').Plan;
}
